/* autogenerated by Processing revision 1281 on 2022-02-28 */
import processing.core.*;
import processing.data.*;
import processing.event.*;
import processing.opengl.*;

import java.util.HashMap;
import java.util.ArrayList;
import java.io.File;
import java.io.BufferedReader;
import java.io.PrintWriter;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.IOException;

public class real_firework extends PApplet {


float gravity=0.00f;
float drag=0.01f;
float life=60;
int total=0;

 public void mousePressed()
{
  fires[i]=new fire(-1,i,mouseX,mouseY,12,0,-8,random(150,255),random(150,255),random(150,255),0);
  i++;
}


fire[] fires=new fire[1000000];
class fire
{
  
  float x,y,r,dx,dy,clr1,clr2,clr3;
  float fire_life=life;
  int exploded,par,me;
  fire(int PAR,int ME,float X,float Y,float R, float DX,float DY,float CLR1,float CLR2,float CLR3,int EXP)
  {
    x=X;y=Y;r=R;dx=DX;dy=DY;clr1=CLR1;clr2=CLR2;clr3=CLR3;par=PAR;me=ME;exploded=EXP;
  }
  
   public void move()
  {
    dy+=gravity-drag*dy;
    if(dx>0)
    {
      dx-=drag*dx;
    }
    else
    {
      dx+=drag*-dx;
    }
    x+=dx;
    y+=dy;
    if(fire_life>0)
    {
      fire_life--;
    }
      
  }
  
   public void display()
  {
    fill(clr1,clr2,clr3,255*fire_life/life);
    stroke(clr1+0.7f*(255-clr1)*fire_life/life,clr2+0.7f*(255-clr1)*fire_life/life,clr3+0.7f*(255-clr1)*fire_life/life,200*fire_life/life);
    strokeWeight(6);
    line(x,y,x+4*dx,y+4*dy);
    
  } 
  
   public void firework()//make new fire 
  {
   
   {
      
        int j,num_fire=20;
        for(j=1;j<=num_fire;j++)
        {
          fires[i+j-1]=new fire(me,i+j-1,x,y,r-2,3*cos((float)j/(num_fire/2)*PI)+random(-1.5f,1.5f),3*sin((float)j/(num_fire/2)*PI)+random(-1.5f,1.5f),clr1,clr2,clr3,exploded+1);
        }
        i+=num_fire;
        
        
        fill(clr1,clr2,clr3,200);
        stroke(clr1,clr2,clr3,100);
        ellipse(x,y,130,130);
        
        clr1=0;clr2=0;clr3=0;
        
   }
  }
  
  
  
  
  
}
int i;

/*

*/
int count=0;
int y=500;
 public void setup()  
{
  /* size commented out by preprocessor */;
  background(0);
  frameRate(60);
  fires[0]=new fire(-1,0,1000,700,12,0,-8,0,200,200,0);
  fires[1]=new fire(-1,0,700,700,12,0,-8,0,200,200,0);
  fires[2]=new fire(-1,0,1300,700,12,0,-8,0,200,200,0);
  i=3;
}

 public void draw()
{
  background(0);
  fill(255);
  textSize(30);
  text(total,100,200);
  int j,k;
  for(j=0;j<i;j++)
  {
   if(fires[j].fire_life>0)
   {
      fires[j].move();
      fires[j].display();
      if(fires[j].exploded==0&&fires[j].fire_life==0)
      {
        fires[j].firework();
      }
    }
    if(fires[j].fire_life>0)
    {
      for(k=j+1;k<i;k++)
      {
        if((abs(fires[j].x-fires[k].x)<=3)&&(abs(fires[j].y-fires[k].y)<=3)&&(fires[j].par!=fires[k].par)&&fires[j].exploded<=2&&fires[k].exploded<=2)
        {
          fires[j].fire_life=0;
          fires[k].fire_life=0;
          fires[j].firework();
          total++;
          break;
        }
      }
    }
  }
}


  public void settings() { fullScreen(); }

  static public void main(String[] passedArgs) {
    String[] appletArgs = new String[] { "real_firework" };
    if (passedArgs != null) {
      PApplet.main(concat(appletArgs, passedArgs));
    } else {
      PApplet.main(appletArgs);
    }
  }
}
